---
title: "Doelmatigheid"
description: | 
  Waarom zijn we met doelmatigheid bezig?
author: 
  - name: "Tim Kops"
    affiliation: "BuurtzorgT"
    affiliation_url: https://www.buurtzorgt.nl
categories:
  - Doelmatigheid
output: 
  distill::distill_article:
    self_contained: false
date: 05-03-2019    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# BuurtzorgT

BuurtzorgT is een kleine en snelgroeiende GGZ-zorgaanbieder, opgericht in 2014. We geven de behandelaars de ruimte zodat zij hun vak weer met plezier kunnen uitoefenen en datgene kunnen wat nodig is voor de cliënten die bij ons in zorg komen. We zijn innovatief en doen tegelijkertijd al precies datgene wat de politiek, de maatschappij, de inspectie en de financiers van ons vragen: behandelen in de omgeving van de cliënt, met hulp van naasten, in samenwerking met betrokken instanties en organisaties en zonder wachttijd. 

Logischerwijs worden er vragen gesteld over wie wij zijn, wat we doen, wat het kost en wat het oplevert. Deze vragen willen wij graag in een breed perspectief beantwoorden. Om te komen tot een volledig beeld van het effect van onze activiteiten zoeken we samenwerking met zorgverzekeraars. Zij hebben de data die ons inhoudelijke verhaal kunnen onderschrijven. Doelmatigheid is hierbij vaak het toverwoord. Op deze website laten we zien hoe wij doelmatigheid onder de loep nemen en geven wij ook onze visie op dit onderwerp


## Wat is doelmatigheid in de GGZ?

BuurtzorgT biedt sociale psychiatrie. Vergelijk het met een fietsenmaker. Wij krijgen klanten met een sterk verroeste ketting, met een kapotte kettingkast en van wie we weten dat ze thuis geen droge stalling hebben. Deze klanten hebben er niets aan als we slechts de roest verwijderen want daarmee zijn ze slechts kortdurend geholpen. Wij gaan twee stappen verder: we maken ook de kettingkast en helpen bij het maken of vinden van een droge stalling.   BuurtzorgT vindt dit de beste manier omdat het de cliënt het beste helpt. Ook is het op langere termijn de goedkoopste manier, zo verwachten wij. Om te weten of onze werkwijze doelmatig is, geldt als eerste stap het definiëren van doelmatigheid. 

> Doelmatigheid gaat om de vraag: heeft een bestede euro zorggeld voldoende effect op hetgeen waaraan het is besteed? 


Doelmatigheid gaat over: | In relatie tot:
----------------------|-------------------------------------------------
Aantal uren inzet BuurtzorgT | Hoe was dit voordat BuurtzorgT betrokken werd? (indien van toepassing)
Prijs per uur inzet BuurtzorgT | De toename van kwaliteit van leven
Kosten inzet andere zorg (opnames, huisarts, medicatie, etc.) | Andere aanbieders met dezelfde doelgroep (de benchmark)



In ons geval gaat het om de psychische gezondheid van de cliënt. Net als in de discussie over wat een extra levensjaar mag kosten als hiervoor behandeling nodig is, is het in de GGZ moeilijk vast te stellen wat een toename van geestelijke gezondheid mag kosten. Daarom kiezen financiers al snel voor een benchmark om een beeld te krijgen bij het nut van een bestede euro. Hierbij geldt de aanname dat de aanbieder met de minste uren inzet per cliënt het meest doelmatig is. Vaak wordt een behandeling hierbij opgesplitst in DBC’s en productgroepen. Er worden dus 4 elementen van doelmatigheid genegeerd:

* zorgconsumptie vóór aanmelding bij BuurtzorgT;

* andere zorgkosten; 

* kwaliteit van leven en het betaalde tarief (zie bovenstaande tabel));

* en er worden 2 elementen die weinig relatie hebben met doelmatigheid toegevoegd (DBC’s en productgroepen). 

Ook worden organisaties met elkaar vergeleken met een (zeer) uiteenlopend zorgprofiel / zeer uiteenlopende doelgroepen. Een betrouwbare benchmark start met het vinden van organisaties met een vergelijkbare doelgroep. In ons geval zijn dat FACT-teams, IHT-teams en PIT-teams.  

BuurtzorgT vindt dat doelmatigheid pas echt kan worden vastgesteld als alle elementen uit de tabel betrokken worden. Doelmatigheid heeft per doelgroep een verschillende betekenis omdat het maximale effect van de bestede euro’s verschillend is. Zo heeft een fietsenmaker klanten met fietsen van verschillende intrinsieke kwaliteit. Het zou onjuist zijn het resultaat van zijn werk aan een oude versleten fiets te vergelijken met het resultaat van zijn werk aan een nieuwe dure fiets waarvan een onderdeel los zit.

Maar hoe onderscheid je doelgroepen? Het is een zeer relevante vraag. Op deze website laten we zien hoe we hierbij te werk gaan met behulp van statistische modellen. We gaan op zoek naar de onderscheidende factoren en brengen in beeld wat het effect hiervan is. Welke onderscheid ontstaat en wat levert dat voor informatie op over doelmatigheid? Wat zijn normale zorgconsumptiepatronen en hoe zijn afwijkingen hierop te verklaren? We werken hierbij met de data van BuurtzorgT. Dat is tegelijkertijd onze bron als onze beperking. Kosten van inzet andere zorg, de hulpverleningsgeschiedenis en de kwaliteit van leven zijn factoren die (nog) ontbreken. Ook zouden we graag elementen betrekken die de maatschappij geld kosten en waarop zorg indirect invloed heeft, zoals UWV-uitkeringen. Het neemt niet weg dat het model dat we bouwen van grote waarde kan zijn bij het gesprek over onze doelmatigheid en onze kijk op het effect van hetgeen we doen.